### ISSUE TITLE
The dataset link is down.

### ISSUE THREAD

**Issue by DarrenTitor** [DegardinBruno/human_activity_anomaly_IJCB20#13]
It was available several days ago, but now the link is down. Thanks in advance :)

**Comment by Sumadera2714** [comment]
me too . I  also want to download this dataset to run this program, it's connect to my graduation thesis :( . So can u upload this dataset if you have downloaded it

**Comment by DegardinBruno** [comment]
Dear @DarrenTitor and @Sumadera2714,

Sorry for my delay! The server is already up and running. Feel free to download it now!
Any further questions, just contact me.

Thank you for your interest!

**Comment by Sumadera2714** [comment]
> 
Thx very much. I am an AI noob，and I want to run your program to study so  that I wish everything can be as same as yours. I can't wait to try this program ：)

**Comment by Sumadera2714** [comment]
> 亲爱的@DarrenTitor和@Sumadera2714，
> 
> 对不起我的延误！服务器已经启动并运行。立即下载！ 任何其他问题，请与我联系。
> 
> 感谢您的关注！

Hey bro,   I have downloaded this dataset ,which directory should I put the dataset in? I don't know how to run this program. ：（

**Comment by DarrenTitor** [comment]
Thanks for your reply. I'll closed this thread  :)
