### ISSUE TITLE
The link of the dataset is down

### ISSUE THREAD

**Issue by caiduoduo12138** [DegardinBruno/human_activity_anomaly_IJCB20#21]
Hi，thanks for your great job. I want to get the dataset, but the link seems to be down.

**Comment by DegardinBruno** [comment]
Hey @caiduoduo12138 , 

Have you accessed to this one? It may take some seconds to load, but it should work now.
http://socia-lab.di.ubi.pt/EventDetection/UBI_FIGHTS.zip

**Comment by caiduoduo12138** [comment]
sorry, it does not  work.  The website can not be accessed normally.

**Comment by caiduoduo12138** [comment]
It seems that I can not access the link http://socia-lab.di.ubi.pt/

**Comment by DegardinBruno** [comment]
If you have a linux OS, can you try with ``wget http://socia-lab.di.ubi.pt/EventDetection/UBI_FIGHTS.zip``  ?
Or equivalent on windows/mac terminal?

**Comment by caiduoduo12138** [comment]
when I run the command in the terminal, wget gives the following output:
wget: unable to resolve host address ‘socia-lab.di.ubi.pt’
I can not ping 'http://socia-lab.di.ubi.pt/' whether I use the VPN.

**Comment by kx-Z** [comment]
I have the same problem，how to solve it？
