### ISSUE TITLE
run inference and data prepare

### ISSUE THREAD

**Issue by carolchenyx** [DegardinBruno/human_activity_anomaly_IJCB20#4]
Thanks for your excellent work. I would like to know how to run the inference.py?  Where I can use the 'root_C3D_dir'? Thank you

**Comment by DegardinBruno** [comment]
@carolchenyx Thank you! We use C3D as our backbone network. The inference.py file will extract the C3D features directly from your video input. The "root_C3D_dir" contains the root directory for C3Dv1.0 in (https://github.com/facebookarchive/C3D).
Have you already installed C3D? (Note that we only use its first version: C3Dv1.0, and not 1.1)

**Comment by carolchenyx** [comment]
Dear Bruno,
Thanks for your quick reply. Now I know how to get the feature, but I
failed to install the C3D. I would like to know do you have some methods to
install it under the CUDA10.2? Thank you.


Bruno Degardin ***@***.***> 于2021年4月12日周一 下午6:31写道：

**Comment by DegardinBruno** [comment]
I understand! Its installation is really tricky...
Usually, we install CUDA first, then cudnn, and finally caffe.
If I remember correctly I installed caffe with (https://caffe.berkeleyvision.org/install_apt.html)
CUDA and cudnn were installed through the NVIDIA tutorials.
Then I installed C3D with the short tutorial here.
![Screenshot from 2021-04-13 12-07-45](https://user-images.githubusercontent.com/61987997/114543268-e4826680-9c50-11eb-9d15-26fd23006ace.png)

**Comment by carolchenyx** [comment]
Thank you for the detailed explanation. I think I need to install this
project in another computer in case of version conflicts. Super thanks
again.

Bruno Degardin ***@***.***> 于2021年4月13日周二 下午7:08写道：

**Comment by DegardinBruno** [comment]
In case you want to try, NVIDIA graphics allow different CUDA versions installed, 10.1 (which is from this project) and 10.2, for example.
Any additional information, just ask!
Thank you for your interest.

**Comment by carolchenyx** [comment]
Thanks DegardinBruno for your useful information^_^
